-- =========================================================================
-- SmartClock — PHASE A  (safe to run now)
--
-- Paste into: Supabase dashboard -> SQL Editor -> New query -> Run.
--
-- Everything here is additive: new columns, tables, functions, indexes. It
-- changes NO permissions, so the live app keeps working exactly as it does
-- today. The RLS lockdown is Phase B, applied after the new code is deployed.
--
-- Written against the ACTUAL production schema, introspected 2026-07-19:
--   employees  : id integer, name, pin (plaintext), is_active  <- NOT "active"
--   managers   : ALREADY EXISTS - id integer, name, pin, created_at
--   job_sites  : id bigint, lat/lng numeric
--   clock_events: 572 rows, 0 open shifts, statuses all in range
--   photo_uploads / time_entries: exist, 0 rows, unused legacy
-- =========================================================================

-- pgcrypto lives in the "extensions" schema on Supabase. Every function below
-- puts it on the search_path explicitly; omitting it makes the `language sql`
-- functions fail at CREATE time, since their bodies are validated immediately.
create extension if not exists pgcrypto with schema extensions;


-- -------------------------------------------------------------------------
-- 1. Where the employee actually was, at clock-in AND clock-out
--
-- The existing lat/lng columns hold the JOB SITE's coordinates, so they are
-- identical for every shift at a site and prove nothing about attendance.
--
-- accuracy_m is stored so a vague fix is never treated as evidence: a reading
-- 400 m out with +/-300 m accuracy is consistent with standing on site.
-- -------------------------------------------------------------------------
alter table public.clock_events
  add column if not exists clock_in_lat           double precision,
  add column if not exists clock_in_lng           double precision,
  add column if not exists clock_in_accuracy_m    double precision,
  add column if not exists clock_in_distance_m    double precision,
  add column if not exists clock_in_within_fence  boolean,
  add column if not exists clock_out_lat          double precision,
  add column if not exists clock_out_lng          double precision,
  add column if not exists clock_out_accuracy_m   double precision,
  add column if not exists clock_out_distance_m   double precision,
  add column if not exists clock_out_within_fence boolean;

comment on column public.clock_events.lat is
  'LEGACY: the job site''s latitude, not the employee''s. Use clock_in_lat.';
comment on column public.clock_events.clock_out_within_fence is
  'NULL = no usable GPS fix. false = confirmed outside the site radius.';


-- -------------------------------------------------------------------------
-- 2. One open shift per employee
--
-- Clock-in was a bare INSERT with no check; the only guard was client state
-- loaded once at mount. Two phones could both insert, and clock-out closed
-- only the first match, orphaning the duplicate permanently and invisibly.
-- -------------------------------------------------------------------------
create unique index if not exists clock_events_one_open_shift_per_employee
  on public.clock_events (employee_name) where clock_out is null;

create index if not exists clock_events_clock_in_idx on public.clock_events (clock_in desc);
create index if not exists clock_events_open_idx     on public.clock_events (clock_out) where clock_out is null;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'clock_events_status_check') then
    alter table public.clock_events add constraint clock_events_status_check
      check (status in ('pending','approved','rejected','edited'));
  end if;
end $$;


-- -------------------------------------------------------------------------
-- 3. Append-only audit trail for manager actions
--
-- Edits overwrite the row, losing the original clock_in/hours, and pack the
-- manager's reason into `notes` behind a delimiter. Since adjusting short
-- shifts is routine and handled face to face, those changes deserve a record.
-- -------------------------------------------------------------------------
create table if not exists public.clock_event_audit (
  id             bigint primary key generated by default as identity,
  created_at     timestamptz not null default now(),
  clock_event_id uuid not null references public.clock_events(id) on delete cascade,
  actor          text not null,
  action         text not null check (action in ('create','edit','approve','reject')),
  reason         text,
  before         jsonb,
  after          jsonb
);

create index if not exists clock_event_audit_event_idx
  on public.clock_event_audit (clock_event_id, created_at desc);


-- -------------------------------------------------------------------------
-- 4. Hashed PIN storage
--
-- Both tables already exist with a plaintext `pin`, so these are ALTERs. The
-- plaintext column is kept for now and dropped in Phase C, once hashed login
-- is confirmed working. NOBODY'S PIN CHANGES.
-- -------------------------------------------------------------------------
alter table public.employees add column if not exists pin_hash text;

alter table public.managers
  add column if not exists pin_hash  text,
  add column if not exists phone     text,          -- feeds the 9:30am / 6pm digests
  add column if not exists is_active boolean not null default true;

-- The legacy plaintext `pin` column is NOT NULL, so adding someone with only a
-- hash fails with 23502. Relaxing it is the correct move rather than writing a
-- placeholder plaintext value: this column carries no meaning once pin_hash is
-- populated, and Phase C drops it outright.
alter table public.employees alter column pin drop not null;
alter table public.managers  alter column pin drop not null;


-- -------------------------------------------------------------------------
-- 5. Reconcile the roster BEFORE adding the unique index
--
-- The employees table is a stale mirror. The names on the timecards are the
-- ones from the hardcoded array, and they disagree with this table:
--
--   'Brandi Larabie' (0 cards)  vs  'Brandy Larabie' (32 cards)
--   'Everist Sundit' (0 cards)  vs  'Evariste Sindayizeruka'
--   'Haydon Rice'    (0 cards)  vs  'Hayden Rice'    (24 cards)
--
-- clock_events.employee_name is denormalised text with no foreign key, so the
-- roster name must match the timecard name exactly or that person's history
-- and open-shift lookup silently stop working. Renaming (rather than inserting
-- a second row) keeps each person's existing PIN untouched.
-- -------------------------------------------------------------------------
update public.employees set name = 'Brandy Larabie'         where name = 'Brandi Larabie';
update public.employees set name = 'Evariste Sindayizeruka' where name = 'Everist Sundit';
update public.employees set name = 'Hayden Rice'            where name = 'Haydon Rice';

-- Off the roster (requested 2026-07-19). Deactivated, NOT deleted: Will Kennedy
-- has 17 time cards and Matthew Larkin has 11, and clock_events has no foreign
-- key to employees, so deleting the row would orphan that history. Setting
-- is_active = false removes them from the clock-in list while every past card,
-- pay period total, and Excel export stays exactly as it is.
--
-- Matthew Larkin was never in this table (he only existed in the hardcoded
-- array), so there is nothing to deactivate — he is simply not added back.
update public.employees set is_active = false where name = 'Will Kennedy';

create unique index if not exists employees_name_unique on public.employees (lower(name));
create unique index if not exists managers_name_unique  on public.managers  (lower(name));


-- -------------------------------------------------------------------------
-- 6. Hash every existing PIN in place
--
-- Reads the plaintext straight from the table, so no PIN is ever typed into a
-- file, a script, or a clipboard. Existing PINs keep working unchanged.
--
-- Idempotent: `where pin_hash is null` means re-running skips anyone already
-- hashed, so this will not clobber a PIN changed later via set_employee_pin().
-- -------------------------------------------------------------------------
update public.employees
   set pin_hash = extensions.crypt(pin, extensions.gen_salt('bf', 10))
 where pin is not null and pin_hash is null;

update public.managers
   set pin_hash = extensions.crypt(pin, extensions.gen_salt('bf', 10))
 where pin is not null and pin_hash is null;


-- -------------------------------------------------------------------------
-- 7. PIN attempt throttling
--
-- With a 4-digit PIN the space is 10,000, so this — not the hash — is what
-- actually stops a brute force. The old pad had no throttle at all.
-- Keyed per identifier so one person mistyping cannot lock out the crew.
-- -------------------------------------------------------------------------
create table if not exists public.auth_attempts (
  identifier   text primary key,
  attempts     integer     not null default 0,
  window_start timestamptz not null default now(),
  locked_until timestamptz
);


-- -------------------------------------------------------------------------
-- 8. Verification and setter functions
--
-- SECURITY DEFINER with EXECUTE revoked from anon/authenticated: reachable
-- only with the service-role key, from a server route that has already
-- rate-limited the caller.
-- -------------------------------------------------------------------------
create or replace function public.verify_employee_pin(p_name text, p_pin text)
returns table (name text)
language sql
security definer
set search_path = public, extensions, pg_temp
as $$
  select e.name from public.employees e
  where lower(e.name) = lower(p_name)
    and e.is_active
    and e.pin_hash is not null
    and e.pin_hash = crypt(p_pin, e.pin_hash);
$$;

-- Returns every active manager whose PIN matches. While the managers share a
-- PIN this returns both rows and the caller records the action as ambiguous.
-- Give them distinct PINs and it returns one row, at which point the audit
-- trail names the actual approver — no code change needed.
create or replace function public.verify_manager_pin(p_pin text)
returns table (name text)
language sql
security definer
set search_path = public, extensions, pg_temp
as $$
  select m.name from public.managers m
  where m.is_active
    and m.pin_hash is not null
    and m.pin_hash = crypt(p_pin, m.pin_hash);
$$;

-- Explicit update-then-insert rather than ON CONFLICT: inferring a conflict
-- target from an expression index (lower(name)) needs awkward double-paren
-- syntax and is easy to get subtly wrong.
create or replace function public.set_employee_pin(p_name text, p_pin text)
returns void
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare v_hash text;
begin
  v_hash := crypt(p_pin, gen_salt('bf', 10));
  update public.employees set pin_hash = v_hash, is_active = true
   where lower(name) = lower(p_name);
  if not found then
    insert into public.employees (name, pin_hash, is_active) values (p_name, v_hash, true);
  end if;
end;
$$;

create or replace function public.set_manager(p_name text, p_pin text, p_phone text default null)
returns void
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare v_hash text;
begin
  v_hash := crypt(p_pin, gen_salt('bf', 10));
  update public.managers
     set pin_hash = v_hash, phone = coalesce(p_phone, phone), is_active = true
   where lower(name) = lower(p_name);
  if not found then
    insert into public.managers (name, pin_hash, phone, is_active)
    values (p_name, v_hash, p_phone, true);
  end if;
end;
$$;

revoke all on function public.verify_employee_pin(text, text) from public, anon, authenticated;
revoke all on function public.verify_manager_pin(text)        from public, anon, authenticated;
revoke all on function public.set_employee_pin(text, text)    from public, anon, authenticated;
revoke all on function public.set_manager(text, text, text)   from public, anon, authenticated;

grant execute on function public.verify_employee_pin(text, text) to service_role;
grant execute on function public.verify_manager_pin(text)        to service_role;
grant execute on function public.set_employee_pin(text, text)    to service_role;
grant execute on function public.set_manager(text, text, text)   to service_role;


-- -------------------------------------------------------------------------
-- Expect: "Success. No rows returned."
--
-- Verify with:
--   select name, pin_hash is not null as hashed, is_active from public.employees order by name;
--   select name, pin_hash is not null as hashed, phone      from public.managers;
-- -------------------------------------------------------------------------
